---
- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      ansible.builtin.apt:
        update_cache: yes
      changed_when: False

  tasks:
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/packages.yml
